# Generated by Django 3.2.7 on 2021-09-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenExpressionCorrectAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenExpressionAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='written_expression.writtenexpressioncorrectans')),
            ],
        ),
        migrations.CreateModel(
            name='WrittenExpresionQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='written_expression.writtenexpressionans')),
            ],
        ),
    ]
