# Generated by Django 3.2.7 on 2021-09-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('written_expression', '0002_rename_writtenexpresionquestions_writtenexpressionquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writtenexpressionans',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='writtenexpressionans',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='writtenexpressionans',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='writtenexpressionans',
            old_name='d',
            new_name='D',
        ),
    ]
